services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
    networks:
      - dd-network
      
  gateway:
    build: ./dd-teachflow-gateway
    ports:
      - "${GATEWAY_PORT}:5000"
    volumes:
      - ./dd-teachflow-gateway/src:/usr/src/app/src
    command: yarn start:dev
    env_file:
      - ./dd-teachflow-gateway/.env.dev
    environment:
      - PORT=5000
      - NATS_URL=nats://nats-server:4222
    networks:
      - dd-network
    depends_on:
      - nats-server
  
  dd-utils:
    build: ./dd-utils
    ports:
      - "5500:5500"
    volumes:
      - ./dd-utils/src:/usr/src/app/src
    command: yarn start:dev
    env_file:
      - ./dd-utils/.env.dev
    environment:
      - PORT=5500
      - NATS_URL=nats://nats-server:4222
    networks:
      - dd-network
    depends_on:
      - utils-db
      - nats-server
  
  utils-db:
    image: postgres:16.2
    container_name: dd-utils-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dd-network

volumes:
  pgdata:
    driver: local

networks:
  dd-network:
      driver: bridge